name: SignalDock Docker Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  docker-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Build Web service
        run: |
          docker build \
            -t signaldock-web:test \
            ./services/web


      - name: Build API service
        run: |
          docker build \
            -t signaldock-api:test \
            ./services/api


      - name: Build Triage service
        run: |
          docker build \
            -t signaldock-triage:test \
            ./services/triage


      - name: Show built images
        run: docker images